In [1]:
using JSON, ProgressMeter, JLD, LightGraphs 

## Community Detection on twitter network using non-negative matrix factorization and graph regularization.
This implements the `DualNMF` algorithm in this paper: [Community Detection in Political Twitter Networks using Nonnegative Matrix Factorization Methods](https://arxiv.org/abs/1608.01771)

Prerequisites:
- the retweet graph as a LightGraphs object
- the user/graph matrix

In [18]:
user_word = JLD.load("/media/henripal/hd1/data/new_mat.jld", "new_mat");
graph = JLD.load("/media/henripal/hd1/data/graph.jld", "graph");

In [19]:
size(user_word,2)

5132

### Building a word/word similarity matrix from the user/word matrix
We iterate on columns because its faster and memory friendly in Julia:

In [20]:
function sparse_similarity(m::SparseMatrixCSC)::SparseMatrixCSC
    normalized_user_word = spzeros(size(m)...)
    norms = [norm(m[:,i]) for i in 1:size(m,2)]
    @showprogress for (col,s) in enumerate(norms)
        s == 0 && continue # What does a "normalized" column with a sum of zero look like?
        normalized_user_word[:,col] = m[:,col]/s
    end
    return normalized_user_word' * normalized_user_word
end


# this builds a LightGraphs graph from a similartiy matrix
function build_graph_from_similarity(similarity::Matrix, cutoff::Float64)::Graph
    length = size(similarity, 1)
    graph = Graph(length)
    for i in 1:length
        for j in 1:i-1
            similarity[i, j] > cutoff && add_edge!(graph, i, j)
        end
    end
    graph
end
    

sparse_similarity (generic function with 1 method)

In [21]:
# this succesively builds the similarity matrix then
# builds the graph from the similarity matrix

cutoff = .4
similarity = sparse_similarity(user_word)
word_graph = build_graph_from_similarity(full(similarity), cutoff)

Progress: 100%|█████████████████████████████████████████| Time: 0:04:16


5132×5132 sparse matrix with 24981772 Float64 nonzero entries:
	[1   ,    1]  =  1.0
	[2   ,    1]  =  0.104883
	[3   ,    1]  =  0.0077162
	[4   ,    1]  =  0.134559
	[5   ,    1]  =  0.0689679
	[6   ,    1]  =  0.0223928
	[7   ,    1]  =  0.00913363
	[8   ,    1]  =  0.146813
	[9   ,    1]  =  0.0788164
	[10  ,    1]  =  0.116557
	⋮
	[5122, 5132]  =  0.120978
	[5123, 5132]  =  0.177761
	[5124, 5132]  =  0.0172602
	[5125, 5132]  =  0.266282
	[5126, 5132]  =  0.195395
	[5127, 5132]  =  0.0338713
	[5128, 5132]  =  0.138883
	[5129, 5132]  =  0.127958
	[5130, 5132]  =  0.300903
	[5131, 5132]  =  0.229402
	[5132, 5132]  =  1.0

### Algorithm
- calculate the Laplacian matrices
- define the update functions
- define the cost function
- iterate the update functions

Some remarks: the cost function is quite expensive, so we do not calculate it everytime. It would be maybe useful to adaptively calculate it?

Some of the helper functions are a little strange looking; this is because these matrices are huge, some are not sparse, and the memory usage can get a little out of control. Hence the column iterations, some precalculations, etc..

In [22]:
# calculating the laplacian matrices and plusminus laplacian:
L_c = laplacian_matrix(graph)
word_laplacian = laplacian_matrix(word_graph)
wl_plus = (abs(word_laplacian)+word_laplacian)/2
wl_minus = (abs(word_laplacian)-word_laplacian)/2
gl_plus = (abs(L_c)+L_c)/2
gl_minus = (abs(L_c)-L_c)/2

1205559×1205559 sparse matrix with 7484416 Int64 nonzero entries:
	[1      ,       1]  =  8
	[2      ,       1]  =  -1
	[3      ,       1]  =  -1
	[4      ,       1]  =  -1
	[5      ,       1]  =  -1
	[6      ,       1]  =  -1
	[7      ,       1]  =  -1
	[8      ,       1]  =  -1
	[9      ,       1]  =  -1
	[1      ,       2]  =  -1
	⋮
	[1205555, 1205555]  =  2
	[234    , 1205556]  =  -1
	[235    , 1205556]  =  -1
	[1205556, 1205556]  =  2
	[11575  , 1205557]  =  -1
	[1205557, 1205557]  =  1
	[94     , 1205558]  =  -1
	[1205558, 1205558]  =  2
	[1205559, 1205558]  =  -1
	[1205558, 1205559]  =  -1
	[1205559, 1205559]  =  1

In [28]:
# parameters and initializing W and U
clusters = 60
α = 10
β = 10
users = size(L_c,1)
words = size(word_laplacian ,1)
W = .5 * spones(sprand(words, clusters, .5))
U = .5 * spones(sprand(users, clusters, .5))


1205559×60 sparse matrix with 36172295 Float64 nonzero entries:
	[2      ,       1]  =  0.5
	[4      ,       1]  =  0.5
	[6      ,       1]  =  0.5
	[9      ,       1]  =  0.5
	[10     ,       1]  =  0.5
	[13     ,       1]  =  0.5
	[14     ,       1]  =  0.5
	[15     ,       1]  =  0.5
	[16     ,       1]  =  0.5
	[19     ,       1]  =  0.5
	⋮
	[1205542,      60]  =  0.5
	[1205547,      60]  =  0.5
	[1205548,      60]  =  0.5
	[1205549,      60]  =  0.5
	[1205550,      60]  =  0.5
	[1205551,      60]  =  0.5
	[1205552,      60]  =  0.5
	[1205553,      60]  =  0.5
	[1205554,      60]  =  0.5
	[1205558,      60]  =  0.5
	[1205559,      60]  =  0.5

In [30]:
# memory friendly update functions

function update_U(U::SparseMatrixCSC, W::SparseMatrixCSC)::SparseMatrixCSC
    WpW = W' * W
    return U .* sqrt((user_word * W + α * gl_minus * U) ./ (U * WpW + α * gl_plus * U))
end

function update_W(U::SparseMatrixCSC, W::SparseMatrixCSC)::SparseMatrixCSC
    UpU = U' * U
    return W .* sqrt((user_word' * U + β * wl_minus * W) ./ (W * UpU + β * wl_plus * W))
end

update_U (generic function with 1 method)

In [32]:
# memory friendly frobenius norms and objective functions

function my_frobenius(uw::SparseMatrixCSC, U::SparseMatrixCSC, W::SparseMatrixCSC)::Float64
    (users, words) = size(uw)
    wp = W'
    clusters = size(U,2)
    result = 0
    @showprogress for j in 1:words
        uwp_j = U*wp[:, j]
        result += norm(uw[:, j] - uwp_j)^2
    end
    result
end

function obj(U::SparseMatrixCSC, W::SparseMatrixCSC)::Float64
    my_frobenius(user_word, U, W) + α * trace(U' * L_c * U) + β * trace(W' * word_laplacian * W)
end

obj (generic function with 1 method)

This is where we run the algorithm. Somewhat time intensive but not crazily so

In [47]:
tolerance = .05
delta = 1000
stride = 10

err = obj(U, W)

while delta > tolerance
    for i in 1:stride
        U = update_U(U, W);
        W = update_W(U, W);
    end
    newerr = obj(U,W)
    delta = abs(newerr - err)
    err = newerr
end

Progress: 100%|█████████████████████████████████████████| Time: 0:09:33


In [49]:
JLD.save("/media/henripal/hd1/data/U_60.jld", "U_60", U)

In [51]:
# another helper functions, assigns the communities based on the highest probability of being in that community

function assign_communities(u::SparseMatrixCSC)
    (n_user, n_cluster) = size(u)
    communities = Array{Int64,1}(n_user)
    @showprogress for user in 1:n_user
        communities[user] = indmax(u[user, :])
    end
    communities
end


assign_communities (generic function with 1 method)

In [52]:
comm = assign_communities(U)

Progress: 100%|█████████████████████████████████████████| Time: 0:00:10


1205559-element Array{Int64,1}:
 19
 27
 31
  7
 19
 19
 59
 22
 18
 31
 31
 25
 44
  ⋮
 41
 25
 41
 21
 51
 57
 10
 17
 31
  9
  2
 30

In [53]:
using Plots

In [55]:
histogram(comm, nbins = 60)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 25 
 
 
 50 
 
 
 0 
 
 
 50000 
 
 
 100000 
 
 
 150000 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

## Some post-processing to vizualize data using projector, and restrict ourselves to the 10k largest accounts.
This is totally in rough draft form

In [10]:
U_60 = JLD.load("/media/henripal/hd1/data/U_60.jld", "U_60")

1205559×60 sparse matrix with 35334538 Float64 nonzero entries:
	[2      ,       1]  =  0.0495808
	[6      ,       1]  =  0.00918191
	[9      ,       1]  =  0.123767
	[10     ,       1]  =  0.000630212
	[13     ,       1]  =  0.00385952
	[14     ,       1]  =  0.00347653
	[15     ,       1]  =  0.00244331
	[16     ,       1]  =  0.000328876
	[19     ,       1]  =  0.00363582
	[20     ,       1]  =  0.00131454
	⋮
	[1205542,      60]  =  8.94298e-39
	[1205547,      60]  =  5.19441e-202
	[1205548,      60]  =  2.42452e-200
	[1205549,      60]  =  7.16569e-5
	[1205550,      60]  =  7.76278e-30
	[1205551,      60]  =  0.0097963
	[1205552,      60]  =  5.43669e-8
	[1205553,      60]  =  1.072e-5
	[1205554,      60]  =  6.15074e-75
	[1205558,      60]  =  0.000951541
	[1205559,      60]  =  0.000741547

In [12]:
using DataFrames

In [25]:
name_followers = readtable("/media/henripal/hd1/data/name_to_follower.csv", header = false);

In [26]:
rename!(name_followers,:x1,:name)
rename!(name_followers,:x2, :followers)

1076038×2 DataFrames.DataFrame
│ Row     │ name              │ followers │
├─────────┼───────────────────┼───────────┤
│ 1       │ "GavaironJ"       │ 5         │
│ 2       │ "bocchijoto"      │ 1834      │
│ 3       │ "cannabinolsen"   │ 1         │
│ 4       │ "angelman61"      │ 32        │
│ 5       │ "alex_latrice21"  │ 199       │
│ 6       │ "turnipkween"     │ 242       │
│ 7       │ "EveMorante"      │ 747       │
│ 8       │ "mwutley"         │ 113       │
│ 9       │ "LetsCllnk"       │ 59        │
│ 10      │ "positivelytaco"  │ 173       │
│ 11      │ "SachaStein"      │ 171       │
⋮
│ 1076027 │ "trena_nauta"     │ 91        │
│ 1076028 │ "TEurit"          │ 74        │
│ 1076029 │ "CamilleVanneste" │ 232       │
│ 1076030 │ "kawaiiPhilip"    │ 342       │
│ 1076031 │ "nahlaels"        │ 2932      │
│ 1076032 │ "superhamps"      │ 155       │
│ 1076033 │ "danvera"         │ 1371      │
│ 1076034 │ "matthewmientka"  │ 26545     │
│ 1076035 │ "EmmaCDickinson"  │ 231       │
│ 1076036 │ "zombiemedic1985" │ 124       │
│ 1076037 │ "kben_ears"       │ 96        │
│ 1076038 │ "RynoDyrt"        │ 173       │

In [32]:
sort!(name_followers, cols= :followers, rev = true);

In [35]:
name_followers = name_followers[1:10000,:]

10000×2 DataFrames.DataFrame
│ Row   │ name              │ followers │
├───────┼───────────────────┼───────────┤
│ 1     │ "MileyCyrus"      │ 31598990  │
│ 2     │ "TheEconomist"    │ 18303980  │
│ 3     │ "POTUS"           │ 14277895  │
│ 4     │ "funnyordie"      │ 13936034  │
│ 5     │ "TIME"            │ 12715214  │
│ 6     │ "ArvindKejriwal"  │ 10276363  │
│ 7     │ "SarahKSilverman" │ 9776677   │
│ 8     │ "jk_rowling"      │ 9056612   │
│ 9     │ "HuffingtonPost"  │ 8868956   │
│ 10    │ "people"          │ 7546839   │
│ 11    │ "lemondefr"       │ 6668668   │
⋮
│ 9989  │ "ughmeIanie"      │ 18765     │
│ 9990  │ "PtdArcole"       │ 18756     │
│ 9991  │ "BlueNRedState"   │ 18756     │
│ 9992  │ "JoshuaDixen"     │ 18755     │
│ 9993  │ "iCelebScoop"     │ 18750     │
│ 9994  │ "BklynEagle"      │ 18750     │
│ 9995  │ "TEENVOGUEITGIRL" │ 18747     │
│ 9996  │ "itsestra"        │ 18744     │
│ 9997  │ "bracealmighty"   │ 18736     │
│ 9998  │ "dragonian3333"   │ 18734     │
│ 9999  │ "spadesmagazine"  │ 18732     │
│ 10000 │ "MsLatina"        │ 18730     │

In [36]:
name_followers[:ind] = [name_to_index[n] for n in name_followers[:name]]

10000-element Array{Int64,1}:
 1105228
  400654
  430428
  519328
   18442
 1024618
 1058073
  701067
  521599
  441624
  928554
   21126
  883751
       ⋮
 1056759
  389300
  861936
 1060834
  628955
  783077
  146505
  687415
  538132
  373521
  903695
  727673

In [38]:
user_vectors = Array{Float64,2}(10000, 60)

10000×60 Array{Float64,2}:
 5.31633e-318  5.26693e-318  5.21753e-318  …  4.09076e-319  3.47501e-319
 5.31633e-318  5.26692e-318  5.21753e-318     4.09081e-319  3.47506e-319
 5.31632e-318  5.26692e-318  5.21751e-318     4.09086e-319  3.47511e-319
 5.31632e-318  5.26691e-318  5.21751e-318     4.09091e-319  3.47516e-319
 5.31631e-318  5.2669e-318   5.21748e-318     4.09096e-319  3.47521e-319
 5.31631e-318  5.26691e-318  5.21749e-318  …  4.09101e-319  3.47526e-319
 5.3163e-318   5.26689e-318  5.21749e-318     4.09106e-319  3.47531e-319
 5.3163e-318   5.2669e-318   5.2175e-318      4.09111e-319  3.47536e-319
 5.31629e-318  5.26689e-318  5.2175e-318      4.09116e-319  3.47541e-319
 5.31629e-318  5.26688e-318  5.21747e-318     4.09121e-319  3.47546e-319
 5.31628e-318  5.26688e-318  5.21747e-318  …  4.09126e-319  3.4755e-319 
 5.31628e-318  5.26687e-318  5.21748e-318     4.09131e-319  3.47555e-319
 5.31627e-318  5.26687e-318  5.21745e-318     4.09136e-319  3.4756e-319 
 ⋮                      

In [41]:
for i in 1:10000, j in 1:60
    user_vectors[i, j] = U_60[name_followers[:ind][i], j]
end

In [43]:
user_cluster = DataFrame(user_vectors)

10000×60 DataFrames.DataFrame
│ Row   │ x1          │ x2          │ x3           │ x4          │ x5          │
├───────┼─────────────┼─────────────┼──────────────┼─────────────┼─────────────┤
│ 1     │ 0.000330843 │ 0.000235566 │ 2.04465e-10  │ 0.0         │ 0.0         │
│ 2     │ 0.0121859   │ 0.00752035  │ 0.0          │ 0.0         │ 0.0         │
│ 3     │ 0.0         │ 0.0         │ 4.02024e-24  │ 0.0         │ 0.0         │
│ 4     │ 0.00177475  │ 0.0         │ 3.89326e-26  │ 0.0         │ 0.0         │
│ 5     │ 0.00978843  │ 0.0         │ 2.30761e-9   │ 0.0         │ 0.0         │
│ 6     │ 0.0         │ 0.0         │ 2.18288e-58  │ 0.0049464   │ 0.0         │
│ 7     │ 0.0         │ 0.0027797   │ 3.39794e-12  │ 0.0         │ 0.0         │
│ 8     │ 0.0212372   │ 0.0         │ 0.0          │ 0.00152144  │ 0.0         │
│ 9     │ 0.0         │ 0.00719583  │ 1.96188e-22  │ 0.00322613  │ 0.0         │
│ 10    │ 0.000735736 │ 0.0         │ 0.0          │ 0.000570369 │ 0.0         │
│ 11    │ 0.0         │ 0.0         │ 4.75518e-38  │ 0.0         │ 0.0         │
⋮
│ 9989  │ 0.000453285 │ 0.00239167  │ 0.0          │ 0.0         │ 0.0         │
│ 9990  │ 0.00842406  │ 0.0         │ 2.0443e-270  │ 0.0         │ 0.0         │
│ 9991  │ 0.0127012   │ 0.0         │ 0.0          │ 0.00411077  │ 0.0         │
│ 9992  │ 0.0         │ 0.0         │ 0.0          │ 0.00439854  │ 0.0         │
│ 9993  │ 0.0         │ 1.85485e-5  │ 0.0          │ 0.0181966   │ 0.0         │
│ 9994  │ 0.00227115  │ 0.000581189 │ 0.0          │ 0.000714301 │ 0.0         │
│ 9995  │ 0.000160781 │ 0.0         │ 0.0          │ 5.09218e-5  │ 0.0         │
│ 9996  │ 0.0         │ 2.80532e-5  │ 6.30273e-13  │ 0.0         │ 0.0         │
│ 9997  │ 0.0         │ 6.4515e-5   │ 1.20943e-70  │ 0.00186836  │ 3.00426e-26 │
│ 9998  │ 0.0         │ 0.0         │ 1.10215e-26  │ 0.0150983   │ 0.0         │
│ 9999  │ 0.0         │ 1.58028e-5  │ 6.52618e-232 │ 0.0         │ 0.0         │
│ 10000 │ 0.0162011   │ 0.0         │ 1.95395e-9   │ 0.102814    │ 0.0         │

│ Row   │ x6          │ x7          │ x8          │ x9          │ x10        │
├───────┼─────────────┼─────────────┼─────────────┼─────────────┼────────────┤
│ 1     │ 0.0         │ 0.0         │ 0.00238467  │ 0.0         │ 0.0        │
│ 2     │ 0.0         │ 0.00279079  │ 0.000439382 │ 0.0         │ 0.0        │
│ 3     │ 7.15231e-5  │ 0.0         │ 0.000511036 │ 0.0         │ 0.0        │
│ 4     │ 0.0         │ 0.00206226  │ 0.0         │ 0.0         │ 0.0        │
│ 5     │ 0.00031452  │ 0.0123258   │ 0.0         │ 0.0155004   │ 0.0        │
│ 6     │ 0.00185327  │ 0.0         │ 0.0         │ 9.24969e-10 │ 0.015323   │
│ 7     │ 8.81402e-5  │ 0.0185283   │ 0.000159886 │ 0.0         │ 0.0        │
│ 8     │ 0.0         │ 0.0143786   │ 0.0         │ 7.12845e-66 │ 0.0180754  │
│ 9     │ 0.0         │ 0.0         │ 0.000311829 │ 0.0         │ 0.0339631  │
│ 10    │ 8.61185e-6  │ 0.00269415  │ 6.769e-6    │ 5.75404e-49 │ 0.00308691 │
│ 11    │ 0.0151673   │ 0.0         │ 0.00624178  │ 0.0         │ 0.0        │
⋮
│ 9989  │ 0.000169857 │ 0.0         │ 0.0         │ 0.0         │ 0.0        │
│ 9990  │ 0.0         │ 0.0         │ 0.0         │ 1.14485e-16 │ 0.0        │
│ 9991  │ 0.00162893  │ 0.00162671  │ 0.0         │ 6.20535e-5  │ 0.0        │
│ 9992  │ 0.0         │ 0.000590191 │ 0.0         │ 0.000132166 │ 0.0        │
│ 9993  │ 0.00434665  │ 0.000207223 │ 0.0152548   │ 5.9031e-8   │ 0.0        │
│ 9994  │ 0.000100711 │ 0.0         │ 0.0         │ 7.76381e-20 │ 0.00563869 │
│ 9995  │ 0.0         │ 0.0         │ 0.0         │ 0.0         │ 0.0319244  │
│ 9996  │ 0.000455804 │ 0.0         │ 0.00167904  │ 0.0         │ 0.00449544 │
│ 9997  │ 0.0         │ 5.35355e-6  │ 0.0         │ 6.93064e-5  │ 0.0        │
│ 9998  │ 0.0         │ 0.0104181   │ 0.0         │ 8.45793e-6  │ 0.117996   │
│ 9999  │ 0.0         │ 0.0         │ 0.0         │ 0.00147132  │ 0.0        │
│ 10000 │ 0.0         │ 0.0         │ 0.0   

In [62]:
class = [indmax(user_vectors[i,:]) for i in 1:10000];
class_freq = zeros(60)
for class_no in class
    class_freq[class_no] = class_freq[class_no]+1
end

In [74]:
best_classes = [i for i in 1:60 if class_freq[i] > 250]

10-element Array{Int64,1}:
  7
 10
 17
 21
 25
 29
 31
 34
 41
 44

In [78]:
new_class = [indmax(user_vectors[i, best_classes]) for i in 1:10000]

10000-element Array{Int64,1}:
  4
  1
 10
  9
  7
  3
  1
  9
  7
  7
  3
  7
  3
  ⋮
  7
  7
  5
  7
  9
  7
  5
  5
  8
  2
  6
  2

In [79]:
name_followers[:class] = string.(new_class)

10000-element Array{String,1}:
 "4" 
 "1" 
 "10"
 "9" 
 "7" 
 "3" 
 "1" 
 "9" 
 "7" 
 "7" 
 "3" 
 "7" 
 "3" 
 ⋮   
 "7" 
 "7" 
 "5" 
 "7" 
 "9" 
 "7" 
 "5" 
 "5" 
 "8" 
 "2" 
 "6" 
 "2" 

In [80]:

writetable("/media/henripal/hd1/data/attributes.tsv",name_followers[:,[:name, :class, :followers]])

In [53]:

writetable("/media/henripal/hd1/data/vectors.tsv",user_cluster, header = false)

In [20]:
df

10×61 DataFrames.DataFrame
│ Row │ x1          │ x2         │ x3          │ x4         │ x5          │
├─────┼─────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ 1   │ 0.0         │ 0.0        │ 0.0         │ 0.0        │ 0.00517256  │
│ 2   │ 0.0495808   │ 0.250884   │ 0.0         │ 0.0        │ 0.0         │
│ 3   │ 0.0         │ 8.71343e-9 │ 0.0         │ 0.0        │ 2.5066e-16  │
│ 4   │ 0.0         │ 0.0        │ 0.0         │ 0.0        │ 6.75701e-9  │
│ 5   │ 0.0         │ 0.0        │ 2.9787e-20  │ 0.0561042  │ 0.0         │
│ 6   │ 0.00918191  │ 0.0        │ 1.16015e-5  │ 0.0        │ 0.000351134 │
│ 7   │ 0.0         │ 0.0        │ 2.39672e-60 │ 0.00263799 │ 0.0         │
│ 8   │ 0.0         │ 0.0451802  │ 9.90117e-10 │ 0.0        │ 0.0024791   │
│ 9   │ 0.123767    │ 0.0        │ 0.0         │ 0.195641   │ 0.0         │
│ 10  │ 0.000630212 │ 0.0        │ 0.0         │ 0.00293096 │ 0.0         │

│ Row │ x6          │ x7         │ x8         │ x9          │ x10         │
├─────┼─────────────┼────────────┼────────────┼─────────────┼─────────────┤
│ 1   │ 0.0269458   │ 0.107755   │ 0.0        │ 0.0         │ 0.0         │
│ 2   │ 0.0         │ 0.0448905  │ 0.146949   │ 0.00606048  │ 0.0295141   │
│ 3   │ 0.00144158  │ 0.00918458 │ 0.00146346 │ 0.0         │ 0.0         │
│ 4   │ 0.0         │ 0.0042903  │ 0.0        │ 0.0         │ 0.0         │
│ 5   │ 0.0         │ 0.100661   │ 0.0        │ 0.0         │ 0.0         │
│ 6   │ 0.0104579   │ 0.0189042  │ 0.024182   │ 0.00811869  │ 0.0193366   │
│ 7   │ 0.00128276  │ 0.0        │ 0.00232613 │ 0.000625355 │ 0.000976757 │
│ 8   │ 0.0         │ 0.0248909  │ 0.049861   │ 0.00534318  │ 0.0         │
│ 9   │ 0.0         │ 0.0        │ 0.216584   │ 0.0142082   │ 0.0891028   │
│ 10  │ 0.000109913 │ 0.0        │ 0.0        │ 0.0         │ 0.00552633  │

│ Row │ x11        │ x12         │ x13        │ x14          │ x15         │
├─────┼────────────┼─────────────┼────────────┼──────────────┼─────────────┤
│ 1   │ 0.0        │ 0.0         │ 0.0        │ 0.0          │ 0.000368133 │
│ 2   │ 0.0890456  │ 0.0         │ 0.0        │ 0.0          │ 0.00020224  │
│ 3   │ 1.40878e-9 │ 3.05569e-6  │ 0.0        │ 2.08197e-18  │ 0.0         │
│ 4   │ 0.0        │ 0.0         │ 0.0        │ 0.0          │ 0.0         │
│ 5   │ 0.00176287 │ 1.84467e-20 │ 0.00281851 │ 0.0          │ 0.0         │
│ 6   │ 0.0        │ 0.0         │ 0.00203696 │ 0.000250148  │ 0.0         │
│ 7   │ 0.0        │ 7.19365e-22 │ 0.0        │ 5.78946e-5   │ 0.000128892 │
│ 8   │ 0.0114296  │ 0.000206747 │ 0.0103953  │ 0.0          │ 0.0         │
│ 9   │ 0.0        │ 0.0         │ 0.0472257  │ 0.00408031   │ 0.0         │
│ 10  │ 0.0        │ 0.0         │ 0.0        │ 5.07094e-111 │ 0.0         │

│ Row │ x16        │ x17         │ x18         │ x19       │ x20        │
├─────┼────────────┼─────────────┼─────────────┼───────────┼────────────┤
│ 1   │ 0.0501996  │ 0.0         │ 0.0163436   │ 0.276983  │ 0.0        │
│ 2   │ 0.00566123 │ 0.0         │ 0.0         │ 0.0       │ 0.0        │
│ 3   │ 0.0203246  │ 0.0         │ 0.0         │ 0.0       │ 0.0        │
│ 4   │ 5.34967e-8 │ 0.0         │ 1.87408e-19 │ 0.0       │ 0.0        │
│ 5   │ 0.0        │ 0.0291893   │ 0.0         │ 0.269572  │ 0.0        │
│ 6   │ 0.0        │ 0.00776464  │ 0.0         │ 0.0797154 │ 0.0144152  │
│ 7   │ 0.00245653 │ 0.000750658 │ 0.00218125  │ 0.0       │ 0.00208378 │
│ 8   │ 0.0        │ 0.0113257   │ 0.0714928   │ 0.0248925 │ 0.0335352  │
│ 9   │ 0.0975845  │ 0.0         │ 0.218439    │ 0.0872451 │ 0.155602   │
│ 10  │ 0.0023344  │ 0.00412763  │ 0.000667164 │ 7.2232e-8 │ 5.77297e-5 │

│ Row │ x21        │ x22        │ x23         │ x24         │ x25         │
├─────┼────────────┼────────────┼─────────────┼─────────────┼─────────────┤
│ 1   │ 0.0        │ 0.0        │ 0.0111386   │ 0.0         │ 0.0         │
│ 2   │ 0.0        │ 0.0583103  │ 0.0         │ 0.0         │ 0.0         │
│ 3   │ 0.0        │ 0.0     